[2025-03-23T15:41:17.722Z] ERROR: uncaughtException: handlePowerCommand is not a function
TypeError: handlePowerCommand is not a function
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\index.js:42:19)
    at EventEmitter.emit (node:events:536:35)
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:40:16)
    at EventEmitter.emit (node:events:524:28)
    at Object.flush (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:73:16)
    at processNodeWithBuffer (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\messages-recv.js:807:12)
[2025-03-23T15:41:52.007Z] ERROR: uncaughtException: handlePowerCommand is not a function
TypeError: handlePowerCommand is not a function
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\index.js:42:19)
    at EventEmitter.emit (node:events:536:35)
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:40:16)
    at EventEmitter.emit (node:events:524:28)
    at flush (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:73:16)
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:109:21
    at async C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\messages-recv.js:681:21
    at async C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\make-mutex.js:19:36
    at async Promise.all (index 0)
    at async handleMessage (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\messages-recv.js:629:13)
[2025-03-23T15:43:33.543Z] ERROR: uncaughtException: handlePowerCommand is not a function
TypeError: handlePowerCommand is not a function
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\index.js:42:19)
    at EventEmitter.emit (node:events:536:35)
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:40:16)
    at EventEmitter.emit (node:events:524:28)
    at Object.flush (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:73:16)
    at processNodeWithBuffer (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\messages-recv.js:807:12)
[2025-03-23T15:44:27.108Z] ERROR: uncaughtException: Unexpected identifier 'was'
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:113
        } else if (connection was 'qr') {
                              ^^^

SyntaxError: Unexpected identifier 'was'
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:6:22)
[2025-03-23T15:44:50.194Z] ERROR: uncaughtException: Unexpected identifier 'was'
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:113
        } else if (connection was 'qr') {
                              ^^^

SyntaxError: Unexpected identifier 'was'
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:6:22)
[2025-03-23T15:46:14.493Z] ERROR: uncaughtException: handlePowerCommand is not a function
TypeError: handlePowerCommand is not a function
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:24:19)
    at EventEmitter.emit (node:events:524:28)
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:40:16)
    at EventEmitter.emit (node:events:524:28)
    at Object.flush (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:73:16)
    at WebSocketClient.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:562:16)
    at WebSocketClient.emit (node:events:524:28)
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:235:35
    at Object.decodeFrame (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\noise-handler.js:144:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[2025-03-23T16:16:23.882Z] ERROR: uncaughtException: isBotOn is not a function
TypeError: isBotOn is not a function
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:42:18)
    at EventEmitter.emit (node:events:536:35)
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:40:16)
    at EventEmitter.emit (node:events:524:28)
    at Object.emit (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:94:23)
    at emitParticipantsUpdate (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\process-message.js:252:56)
    at processMessage (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\process-message.js:269:17)
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\chats.js:739:43
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:105:42
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\messages-recv.js:590:31
[2025-03-23T16:16:36.714Z] ERROR: uncaughtException: isBotOn is not a function
TypeError: isBotOn is not a function
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:42:18)
    at EventEmitter.emit (node:events:536:35)
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:40:16)
    at EventEmitter.emit (node:events:524:28)
    at Object.emit (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:94:23)
    at emitParticipantsUpdate (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\process-message.js:252:56)
    at processMessage (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\process-message.js:269:17)
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\chats.js:739:43
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:105:42
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\messages-recv.js:590:31
[2025-03-23T16:16:49.081Z] ERROR: uncaughtException: isBotOn is not a function
TypeError: isBotOn is not a function
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:42:18)
    at EventEmitter.emit (node:events:536:35)
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:40:16)
    at EventEmitter.emit (node:events:524:28)
    at Object.emit (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:94:23)
    at emitParticipantsUpdate (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\process-message.js:252:56)
    at processMessage (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\process-message.js:269:17)
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\chats.js:739:43
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:105:42
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\messages-recv.js:590:31
[2025-03-23T16:21:30.250Z] ERROR: uncaughtException: handlePowerCommand is not a function
TypeError: handlePowerCommand is not a function
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:30:23)
    at EventEmitter.emit (node:events:536:35)
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:40:16)
    at EventEmitter.emit (node:events:524:28)
    at Object.flush (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:73:16)
    at WebSocketClient.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:562:16)
    at WebSocketClient.emit (node:events:524:28)
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:235:35
    at Object.decodeFrame (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\noise-handler.js:144:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[2025-03-23T16:21:47.016Z] ERROR: uncaughtException: handlePowerCommand is not a function
TypeError: handlePowerCommand is not a function
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:30:23)
    at EventEmitter.emit (node:events:536:35)
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:40:16)
    at EventEmitter.emit (node:events:524:28)
    at Object.flush (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:73:16)
    at WebSocketClient.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:562:16)
    at WebSocketClient.emit (node:events:524:28)
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:235:35
    at Object.decodeFrame (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\noise-handler.js:144:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[2025-03-23T16:23:51.900Z] ERROR: uncaughtException: handlePowerCommand is not a function
TypeError: handlePowerCommand is not a function
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:30:23)
    at EventEmitter.emit (node:events:536:35)
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:40:16)
    at EventEmitter.emit (node:events:524:28)
    at Object.flush (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:73:16)
    at processNodeWithBuffer (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\messages-recv.js:807:12)
[2025-03-23T16:30:03.360Z] ERROR: uncaughtException: handlePowerCommand is not a function
TypeError: handlePowerCommand is not a function
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:22:23)
    at EventEmitter.emit (node:events:524:28)
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:40:16)
    at EventEmitter.emit (node:events:524:28)
    at flush (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:73:16)
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:109:21
    at async C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\messages-recv.js:681:21
    at async C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\make-mutex.js:19:36
    at async Promise.all (index 0)
    at async handleMessage (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\messages-recv.js:629:13)
[2025-03-23T18:02:14.772Z] ERROR: uncaughtException: Identifier 'axios' has already been declared
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:10
const axios = require('axios');
      ^

SyntaxError: Identifier 'axios' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:7:24)
[2025-03-23T18:03:56.781Z] ERROR: uncaughtException: Identifier 'axios' has already been declared
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:10
const axios = require('axios');
      ^

SyntaxError: Identifier 'axios' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:7:24)
[2025-03-23T18:04:09.089Z] ERROR: uncaughtException: Identifier 'axios' has already been declared
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:10
const axios = require('axios');
      ^

SyntaxError: Identifier 'axios' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:7:24)
[2025-03-23T18:04:40.842Z] ERROR: uncaughtException: Identifier 'axios' has already been declared
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:10
const axios = require('axios');
      ^

SyntaxError: Identifier 'axios' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:7:24)
[2025-03-23T18:07:37.683Z] ERROR: uncaughtException: Identifier 'axios' has already been declared
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:10
const axios = require('axios');
      ^

SyntaxError: Identifier 'axios' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:7:24)
[2025-03-23T18:08:15.636Z] ERROR: uncaughtException: Identifier 'axios' has already been declared
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:10
const axios = require('axios');
      ^

SyntaxError: Identifier 'axios' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:7:24)
[2025-03-23T18:09:46.810Z] ERROR: uncaughtException: Identifier 'axios' has already been declared
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:10
const axios = require('axios');
      ^

SyntaxError: Identifier 'axios' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:7:24)
[2025-03-23T18:10:45.446Z] ERROR: uncaughtException: Identifier 'axios' has already been declared
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:10
const axios = require('axios');
      ^

SyntaxError: Identifier 'axios' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:7:24)
[2025-03-23T18:12:42.648Z] ERROR: uncaughtException: Identifier 'axios' has already been declared
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:10
const axios = require('axios');
      ^

SyntaxError: Identifier 'axios' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:7:24)
[2025-03-23T18:12:56.115Z] ERROR: uncaughtException: Identifier 'axios' has already been declared
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:10
const axios = require('axios');
      ^

SyntaxError: Identifier 'axios' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:7:24)
[2025-03-23T18:13:58.483Z] ERROR: uncaughtException: Identifier 'axios' has already been declared
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:10
const axios = require('axios');
      ^

SyntaxError: Identifier 'axios' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:7:24)
[2025-03-23T18:17:32.918Z] ERROR: uncaughtException: Identifier 'axios' has already been declared
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:10
const axios = require('axios');
      ^

SyntaxError: Identifier 'axios' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:7:24)
[2025-03-23T18:20:01.128Z] ERROR: uncaughtException: Identifier 'axios' has already been declared
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:10
const axios = require('axios');
      ^

SyntaxError: Identifier 'axios' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:7:24)
[2025-03-23T18:23:10.957Z] ERROR: uncaughtException: Identifier 'axios' has already been declared
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:10
const axios = require('axios');
      ^

SyntaxError: Identifier 'axios' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:7:24)
[2025-03-23T19:36:10.789Z] ERROR: uncaughtException: Identifier 'cron' has already been declared
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:109
const cron = require('node-cron');
      ^

SyntaxError: Identifier 'cron' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:7:24)
[2025-03-23T20:00:44.618Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T20:06:42.024Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T20:07:27.066Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T20:10:12.283Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T20:10:28.544Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T20:10:52.389Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T20:41:42.416Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T20:53:27.610Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T20:56:27.854Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T20:57:36.917Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T20:58:25.505Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T21:00:07.138Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T21:01:39.915Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T21:02:29.480Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T21:07:50.455Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T21:14:47.456Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T21:17:21.556Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T21:17:50.413Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T21:19:38.325Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T21:20:38.183Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T21:31:51.273Z] ERROR: uncaughtException: Identifier 'handleCommand' has already been declared
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:175
    async function handleCommand(sock, chatId, command, args) {
    ^

SyntaxError: Identifier 'handleCommand' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T21:32:13.745Z] ERROR: uncaughtException: Identifier 'handleCommand' has already been declared
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:175
    async function handleCommand(sock, chatId, command, args) {
    ^

SyntaxError: Identifier 'handleCommand' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T21:33:07.437Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:179
            await scheduleQuote(sock, chatId, time);
            ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T21:35:00.457Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:191
        await commonCommands.listBotsInGroup(sock, chatId);
        ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T21:35:45.158Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:202
            const { error } = await supabase
                              ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-23T21:42:31.323Z] ERROR: uncaughtException: formatMessage is not a function
TypeError: formatMessage is not a function
    at logInfo (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\utils\logger.js:27:29)
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\index.js:47:17)
    at EventEmitter.emit (node:events:536:35)
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:40:16)
    at EventEmitter.emit (node:events:524:28)
    at Object.emit (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:94:23)
    at WebSocketClient.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:514:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[2025-03-23T22:17:13.702Z] ERROR: uncaughtException: axiosRetry is not a function
TypeError: axiosRetry is not a function
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:14:1)
    at Module._compile (node:internal/modules/cjs/loader:1562:14)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:7:24)
[2025-03-23T22:20:13.861Z] ERROR: uncaughtException: axiosRetry is not a function
TypeError: axiosRetry is not a function
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\commonCommands.js:14:1)
    at Module._compile (node:internal/modules/cjs/loader:1562:14)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:7:24)
[2025-03-24T06:11:38.137Z] ERROR: uncaughtException: Cannot find module '../utils/formatResponse'
Require stack:
- C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js
- C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js
- C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\index.js
Error: Cannot find module '../utils/formatResponse'
Require stack:
- C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js
- C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js
- C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1244:15)
    at Function._load (node:internal/modules/cjs/loader:1070:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:23:26)
    at Module._compile (node:internal/modules/cjs/loader:1562:14)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
[2025-03-24T15:52:19.395Z] ERROR: uncaughtException: Cannot read properties of undefined (reading 'me')
TypeError: Cannot read properties of undefined (reading 'me')
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:548:25
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
[2025-03-24T15:55:17.933Z] ERROR: uncaughtException: Cannot read properties of undefined (reading 'me')
TypeError: Cannot read properties of undefined (reading 'me')
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:548:25
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
[2025-03-24T15:58:31.997Z] ERROR: uncaughtException: Cannot read properties of undefined (reading 'me')
TypeError: Cannot read properties of undefined (reading 'me')
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:548:25
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
[2025-03-24T15:59:43.548Z] ERROR: uncaughtException: Cannot read properties of undefined (reading 'me')
TypeError: Cannot read properties of undefined (reading 'me')
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:548:25
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
[2025-03-24T16:05:06.948Z] ERROR: uncaughtException: Cannot read properties of undefined (reading 'me')
TypeError: Cannot read properties of undefined (reading 'me')
    at C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:548:25
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
[2025-03-24T16:35:32.916Z] ERROR: uncaughtException: Identifier 'handleAntiDelete' has already been declared
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:23
const { handleAntiDelete, initializeMessageCache, enableAntiDelete, disableAntiDelete } = require('./message-controller/antiDelete');
        ^

SyntaxError: Identifier 'handleAntiDelete' has already been declared
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\bot\bot.js:2:66)
[2025-03-25T05:54:36.272Z] ERROR: uncaughtException: Cannot read properties of undefined (reading 'id')
TypeError: Cannot read properties of undefined (reading 'id')
    at Object.sendMessage (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\messages-send.js:595:48)
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\index.js:49:28)
    at EventEmitter.emit (node:events:536:35)
    at EventEmitter.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:40:16)
    at EventEmitter.emit (node:events:524:28)
    at Object.emit (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Utils\event-buffer.js:94:23)
    at Timeout.genPairQR [as _onTimeout] (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\node_modules\@whiskeysockets\baileys\lib\Socket\socket.js:485:16)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
[2025-03-25T07:34:50.103Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\adminActions.js:14
    await toggleViewOnce(sock, chatId, sender, isGroup, args);
    ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:9:23)
[2025-03-25T07:36:51.309Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\adminActions.js:14
    await toggleViewOnce(sock, chatId, sender, isGroup, args);
    ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:9:23)
[2025-03-25T07:37:30.969Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\adminActions.js:14
    await toggleViewOnce(sock, chatId, sender, isGroup, args);
    ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:9:23)
[2025-03-25T07:37:58.549Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\adminActions.js:14
    await toggleViewOnce(sock, chatId, sender, isGroup, args);
    ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:9:23)
[2025-03-25T07:39:31.107Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\adminActions.js:14
    await toggleViewOnce(sock, chatId, sender, isGroup, args);
    ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:9:23)
[2025-03-25T07:42:36.339Z] ERROR: uncaughtException: await is only valid in async functions and the top level bodies of modules
C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\adminActions.js:14
    await toggleViewOnce(sock, chatId, sender, isGroup, args);
    ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at wrapSafe (node:internal/modules/cjs/loader:1512:18)
    at Module._compile (node:internal/modules/cjs/loader:1534:20)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:9:23)
[2025-03-25T09:14:31.407Z] ERROR: uncaughtException: repostViewOnceMedia is not defined
ReferenceError: repostViewOnceMedia is not defined
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\viewOnceHandler.js:137:5)
    at Module._compile (node:internal/modules/cjs/loader:1562:14)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1335:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (C:\Users\ADMIN\Documents\Techitoon-Bot-AI\src\message-controller\messageHandler.js:24:119)
